//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidsoft.Reply.Parsers.AnsiMhDi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidsoft.Reply.Parsers.AnsiMhDi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header.
        /// </summary>
        internal static string Ansi_Mh10_8_2_001 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trailer.
        /// </summary>
        internal static string Ansi_Mh10_8_2_002 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records provided..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_001 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format. No format {0} provided..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_002 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_003 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field. No data identifier..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_004 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation for DI{0} timed out..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_005 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity value cannot be null for DI{0}..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_006 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value{0} is invalid for DI {1}..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_007 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is invalid for DI{0}..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_008 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data identifier {0}..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_009 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data identifier..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_010 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value{0} does not match the specified pattern for the data element..
        /// </summary>
        internal static string Ansi_Mh10_8_2_Error_011 {
            get {
                return ResourceManager.GetString("Ansi_Mh10_8_2_Error_011", resourceCulture);
            }
        }
    }
}
