// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1010:Opening square brackets should be spaced correctly", Justification = "<Approved>", Scope = "member", Target = "~F:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier._exceptions")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "<Approved>")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.#ctor(Solidsoft.Reply.Parsers.Common.ParserException,System.Int32,System.String)")]

[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.EntityResolver")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Approved>", Scope = "member", Target = "~F:Solidsoft.Reply.Parsers.AnsiMhDi.DataIdentifier.Unrecognised")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.Category")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.#ctor(Solidsoft.Reply.Parsers.Common.ParserException,System.Int32,Solidsoft.Reply.Parsers.Common.IResolvedEntity)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.#ctor(Solidsoft.Reply.Parsers.Common.ParserException,System.Int32,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.#ctor(System.Int32,System.String,System.Int32,System.String,System.String,System.String,System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.AddException(Solidsoft.Reply.Parsers.Common.ParserException)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~P:Solidsoft.Reply.Parsers.AnsiMhDi.Descriptors.EntityDescriptors.Pattern")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~P:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.Exceptions")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~P:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.IsError")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1101:Prefix local calls with this", Justification = "<Approved>", Scope = "member", Target = "~P:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.IsFatal")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "<Approved>", Scope = "member", Target = "~F:Solidsoft.Reply.Parsers.AnsiMhDi.EntityResolver.Descriptors")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.EntityResolver.GetDescriptors(System.Int32)~Solidsoft.Reply.Parsers.AnsiMhDi.Descriptors.EntityDescriptors")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.EntityResolver.Resolve(System.String,System.String,System.Int32,System.Boolean)~Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.EntityResolver.Validate(Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier)~Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.Extensions.ToInvariantString(System.Char)~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.Extensions.ToInvariantUpper(System.String)~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.Parser.Parse(System.String,System.Action{Solidsoft.Reply.Parsers.Common.IResolvedEntity},System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.#ctor(Solidsoft.Reply.Parsers.Common.ParserException,System.Int32,Solidsoft.Reply.Parsers.Common.IResolvedEntity)")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.#ctor(Solidsoft.Reply.Parsers.Common.ParserException,System.Int32,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.#ctor(System.Int32,System.String,System.Int32,System.String,System.String,System.String,System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~M:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.AddException(Solidsoft.Reply.Parsers.Common.ParserException)")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "member", Target = "~P:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier.IsFatal")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.Category")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.DataIdentifier")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.Descriptors.EntityDescriptors")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.EntityResolver")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.Extensions")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.Parser")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "<Approved>", Scope = "type", Target = "~T:Solidsoft.Reply.Parsers.AnsiMhDi.ResolvedDataIdentifier")]
